import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Studio sidebar collapse preference is persisted in a cookie so the root
// layout can render `<html data-studio-sidebar-collapsed>` with the correct
// value SSR-side — eliminating the flash and the hydration mismatch entirely.
// Cookie name + values are mirrored in `components/lacquer/sidebar/sidebar-shell.client.tsx`.
const SIDEBAR_COOKIE = "tn-studio-sidebar-collapsed";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const collapsed = (await cookies()).get(SIDEBAR_COOKIE)?.value === "1";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-studio-sidebar-collapsed={collapsed ? "true" : "false"}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
